# permissions for end users to view hellos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hello-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: helloworld
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: kustomize
  name: hello-viewer-role
rules:
- apiGroups:
  - action.kuan.io
  resources:
  - hellos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - action.kuan.io
  resources:
  - hellos/status
  verbs:
  - get
